# Generated by Django 5.2.6 on 2025-09-19 13:55

from django.db import migrations


def fix_corrupted_variations(apps, schema_editor):
    """Fix any CartItem records where variations is not a dict"""
    CartItem = apps.get_model('cart', 'CartItem')

    corrupted_items = []
    for item in CartItem.objects.all():
        if not isinstance(item.variations, dict):
            item.variations = {}
            corrupted_items.append(item)

    # Bulk update to fix corrupted variations
    if corrupted_items:
        CartItem.objects.bulk_update(corrupted_items, ['variations'])
        print(f"Fixed {len(corrupted_items)} corrupted cart items")


def reverse_fix_corrupted_variations(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(fix_corrupted_variations, reverse_fix_corrupted_variations),
    ]
