# Generated by Django 5.2.6 on 2025-09-19 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Product"),
                            ("variable", "Variable Product"),
                            ("multi-variable", "Multi-Variable Product"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=50, unique=True)),
                ("in_stock", models.BooleanField(default=True)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                (
                    "featured_image",
                    models.URLField(blank=True, help_text="URL to product image"),
                ),
                (
                    "gallery_images",
                    models.JSONField(
                        blank=True, default=list, help_text="List of image URLs"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=20)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("quality", models.CharField(blank=True, max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sku", models.CharField(blank=True, max_length=50, unique=True)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("in_stock", models.BooleanField(default=True)),
                ("featured_image", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "size", "color", "quality")},
            },
        ),
    ]
